### PR TITLE
Update development-in-the-kyma-environment-606ec61.md

### PR DESCRIPTION
**Pull request by mado0803**
Hello colleagues,

I suggest pointing out that customers can extend all flavours of S/4HANA: self-hosted, SAP-hosted (fka. private edition), and public cloud.

Best regards,
Marco

### CODE REVIEW

**Comment by NHingerl** [comment]
Hi @mado0803, thanks for your suggestion! 
I'll make the change right away. 

You can see the update after the next release of the SAP BTP documentation.

Cheers, Nina

**Comment by NHingerl** [comment]
And I'd merge this if the check recognized that I have indeed signed the CLA.

image

**Comment by nikolasimeonov77** [comment]
Hi @mado0803,
Could you please sign the CLA at https://cla-assistant.io/SAP-docs/btp-cloud-platform?pullRequest=160 so that we can process your request?

Thanks!

Nikola

**Comment by mado0803** [comment]
> Thank you for your valuable content contribution, @mado0803! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://people.sap.com/marco.dorn

**Pull request merged**
