### PR TITLE
fix: add missing closing ' quote

### PR DESCRIPTION
**Pull request by gregorwolf**

### CODE REVIEW

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by gregorwolf** [comment]
Should I do anything about the Markdown linter issues @DavidMitreski5 ?

**Comment by DavidMitreski5** [comment]
Hi @gregorwolf, we will see what Petya's decision is, I automatically assigned her since she is the author of this topic.

**Comment by petiansap** [comment]
Hi @gregorwolf, yes you can fix the Markdown linter issues as you find appropriate. Thank you very much for your help!

**Comment by gregorwolf** [comment]
@petiansap I'm wondering why this issues occur as I haven't changed anything there. Also I'm not shure about the suggested changes. Is thre a documentation why there are suggested?

**Comment by petiansap** [comment]
@gregorwolf, I haven't had such issues so far. The transfer of the documentation is automatic. @nikolasimeonov77 do you know why the issues that Gregor mentions occur?

**Comment by nikolasimeonov77** [comment]
> @gregorwolf, I haven't had such issues so far. The transfer of the documentation is automatic. @nikolasimeonov77 do you know why the issues that Gregor mentions occur?

Hi all,
The linter checks if the document is complying with our writing guidelines. As you know, it is required to use title case for title and the check for this. Please correct the title here in the DITA CCMS, and the check will be green.

**Comment by gregorwolf** [comment]
Hi @nikolasimeonov77, but it seems to me that the document I've changed wasn't complying to the linter rules before I started to edit. I would expect that if such rules are in place there are applied in an automatic process before manual editing is started. I'm happy to update my PR when an automatic update was done.

**Comment by nikolasimeonov77** [comment]
> Hi @nikolasimeonov77, but it seems to me that the document I've changed wasn't complying to the linter rules before I started to edit. I would expect that if such rules are in place there are applied in an automatic process before manual editing is started. I'm happy to update my PR when an automatic update was done.

@qmacro Can you help here? Is it possible to apply the linter rules before the document is edited?

**Comment by nikolasimeonov77** [comment]
> Hi @nikolasimeonov77 - not sure what you mean by "apply the linter rules" here - do you mean run the checks, or auto correct any issues? There shouldn't be any content in the Markdown that doesn't comply, as the linter rules here are supposed to reflect what is also implemented internally.

Hi all,
I did not mean that @gregorwolf is supposed to fix our issue. Not at all, sorry. I meant that an admin with more permissions can fix it here too. However, we need to improve this process so that the linter passes before our GitHub contributors when everything looks good for the contributor.

**Comment by nikolasimeonov77** [comment]
The closing quote is fixed in both examples and the documentastion will be uploaded on SAP Help Portsal with the next release on January 12th.

**Comment by gregorwolf** [comment]
Thank you @nikolasimeonov77 for merging. Is the linter issue resolved?

**Comment by nikolasimeonov77** [comment]
Hi @gregorwolf,
Yes, we are planning to remove the linter check for title case as it is done in our system too. It won't show up as an issue next time.

Thanks!

Nikola

**Comment by qmacro** [comment]
Hey @gregorwolf we [removed the titlecase rule](https://github.com/SAP-docs/btp-cloud-platform/commit/54289945d29ed673c2eff9ba1d6303d5589cec29) 👍

HNY!

**Pull request merged**
