### PR TITLE
Correct quotes in JSON and ABAP samples

### PR DESCRIPTION
**Pull request by gregorwolf**
Correct quotes in JSON and ABAP samples and add Code formatting language

### CODE REVIEW

**Comment by felixdraeger** [comment]
Changes will be implemented.

**Comment by gregorwolf** [comment]
@felixdraeger can't the PR be merged? Will you need to do the updates in a different system?

**Comment by felixdraeger** [comment]
@gregorwolf The pull request will be merged once the changes are made.

**Comment by gregorwolf** [comment]
So do I get it right that the changes are done in a different system?

**Comment by felixdraeger** [comment]
Yes that's correct.

**Comment by gregorwolf** [comment]
So would it be easier to just provide an issue instead of the PR?

**Pull request closed without merging**
