### PR TITLE
Change System User from General to 'Additional'

### PR DESCRIPTION
**Pull request by MartinStenzig**
There is no field called System User in the general parameter section. To make this procedure work you have to add the Key: SystemUser to the Additional Properties list.

As is the current documentation does not lead to a successful outcome. I for one thought I have to put the Username into the existing field of "Token Service User"

### CODE REVIEW

**Comment by je-hal** [comment]
@MartinStenzig: Thank you for your feedback, and sorry for the very belated response. Your proposal was forwarded to the responsible author and we'll get back to you if we need further information.

**Comment by ekaterina-mitova** [comment]
Hi @MartinStenzig, 

Thank you for your valuable contribution. I checked with my dev colleagues. Indeed, the SystemUser property is part of the additional properties. I will update the respective documentation and it will be published with the next release. 

Best regards, 
Ekaterina

**Comment by MartinStenzig** [comment]
My community id is: martin.stenzig3  From: sap-doc-bot[bot] ***@***.***>Date: Thursday, May 12, 2022 at 07:25To: SAP-docs/btp-cloud-platform ***@***.***>Cc: Martin Stenzig ***@***.***>, Mention ***@***.***>Subject: Re: [SAP-docs/btp-cloud-platform] Change System User from General to 'Additional' (PR #60)[EXTERNAL]Thank you for your valuable content contribution, @MartinStenzig! So that we can recognize your contribution in SAP Community, please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:https://people.sap.com/your-user-nameThanks!—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by je-hal** [comment]
https://people.sap.com/martin.stenzig3

**Comment by MartinStenzig** [comment]
Yes, my community profile is: https://people.sap.com/martin.stenzig3

**Comment by qmacro** [comment]
Sorry @MartinStenzig it's all my fault that this badge assignment is not done yet. I apologise! It will be addressed soon.

**Pull request merged**
