### PR TITLE
enable-parallel-deployments, revised the note about resource deployment

### PR DESCRIPTION
**Pull request by sbarzaghialteaup**
Just to clarify the missing of relation between the parameter `enable-parallel-deployments` and the resources process

### CODE REVIEW

**Comment by DavidMitreski5** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by je-hal** [comment]
@lilyanarangelova: Our markdown linter brings up an error, because the header level changes from a first level header ('#') to a third level header ('###'). Is that something you could correct as well?

**Comment by nikolasimeonov77** [comment]
> @lilyanarangelova: Our markdown linter brings up an error, because the header level changes from a first level header ('#') to a third level header ('###'). Is that something you could correct as well?

Thanks Jens for reporting this. I've just fixed it.

**Comment by je-hal** [comment]
> > @lilyanarangelova: Our markdown linter brings up an error, because the header level changes from a first level header ('#') to a third level header ('###'). Is that something you could correct as well?
> 
> Thanks Jens for reporting this. I've just fixed it.

@nikolasimeonov77: Did you also fix it in DITA?

**Comment by nikolasimeonov77** [comment]
> > > @lilyanarangelova: Our markdown linter brings up an error, because the header level changes from a first level header ('#') to a third level header ('###'). Is that something you could correct as well?
> > 
> > 
> > Thanks Jens for reporting this. I've just fixed it.
> 
> @nikolasimeonov77: Did you also fix it in DITA?

Hi Jens,
Thanks! Yes, it's fixed in DITA too. Subsections were wrongfully used instead of sections.

Nikola

**Comment by lilyanarangelova** [comment]
> > > > @lilyanarangelova: Our markdown linter brings up an error, because the header level changes from a first level header ('#') to a third level header ('###'). Is that something you could correct as well?
> > > 
> > > 
> > > Thanks Jens for reporting this. I've just fixed it.
> > 
> > 
> > @nikolasimeonov77: Did you also fix it in DITA?
> 
> Hi Jens, Thanks! Yes, it's fixed in DITA too. Subsections were wrongfully used instead of sections.
> 
> Nikola

Thank you, Nikola!

**Review by lilyanarangelova — APPROVED** [review]

**Comment by sbarzaghialteaup** [comment]
https://people.sap.com/sbarzaghi

**Pull request merged**
