### PR TITLE
Delete duplicate field for category Security Event

### PR DESCRIPTION
**Pull request by Nikola-Popov**

### CODE REVIEW

**Comment by PlamiIG** [comment]
Thank you for your feedback! We’ll look into it and come back to you if we have any questions.

**Comment by petiansap** [comment]
The documentation is updated. @Nikola-Popov, thank you very much for your contribution!

**Comment by Nikola-Popov** [comment]
607723

**Comment by Nikola-Popov** [comment]
> Thank you for your valuable content contribution, @Nikola-Popov! So that we can [recognize your contribution in the SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please check your SAP Community user ID (this is a number) in your [personal settings page](https://community.sap.com/t5/user/myprofilepage/tab/personal-profile) and share it with us in a reply to this comment. Make sure you just include the number in the reply.
> 
> Your user ID is displayed as follows:
> 
> **Change display name for User ID N**
> 
> where N is your user ID. For example, [53 is the user ID of the user 'qmacro'](https://community.sap.com/t5/user/viewprofilepage/user-id/53).
> 
> Please note that we are currently refactoring our profile and badge system on the SAP Community, and will start assigning badges again when that's complete.



> Thank you for your valuable content contribution, @Nikola-Popov! So that we can [recognize your contribution in the SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please check your SAP Community user ID (this is a number) in your [personal settings page](https://community.sap.com/t5/user/myprofilepage/tab/personal-profile) and share it with us in a reply to this comment. Make sure you just include the number in the reply.
> 
> Your user ID is displayed as follows:
> 
> **Change display name for User ID N**
> 
> where N is your user ID. For example, [53 is the user ID of the user 'qmacro'](https://community.sap.com/t5/user/viewprofilepage/user-id/53).
> 
> Please note that we are currently refactoring our profile and badge system on the SAP Community, and will start assigning badges again when that's complete.

607723

**Pull request closed without merging**
