### PR TITLE
Switch to new global Cockpit URL

### PR DESCRIPTION
**Pull request by swendlandt**

### CODE REVIEW

**Review by abiskop — APPROVED** [review]
Looks good to me!

**Comment by annawenger20** [comment]
Thanks, @swendlandt and @abiskop!
@Madeline-Schaefer can you take care of this and then merge, please.

**Review by Madeline-Schaefer — APPROVED** [review]

**Comment by Madeline-Schaefer** [comment]
@annawenger20,

Yes, of course, I checked the documentation and changed the URLs. But I cannot merge anything, it's telling me that I'm not authorized to merge this PR.

**Comment by sdanter** [comment]
Topic will be updated with the next documentation release

**Pull request merged**
