### PR TITLE
Add chapter mark for SapMachine into TOC

### PR DESCRIPTION
**Pull request by MahatmaFatalError**

### CODE REVIEW

**Comment by DavidMitreski5** [comment]
@MahatmaFatalError 
Just a reminder if you have resolved this issue, please close it!

**Comment by MahatmaFatalError** [comment]
> @MahatmaFatalError Just a reminder if you have resolved this issue, please close it!

I want to get this merged since the chapter mark was still missing ;)

**Comment by Joysie** [comment]
Hi Mahatma,

Did you mean this section and topic: 
https://help.sap.com/docs/BTP/65de2977205c403bbc107264b8eccf4b/b8cda61d3d984e259f1de8816e52ec47.html 

If you do - **SapMachine** is now in it :)

**Comment by Joysie** [comment]
Hi @MahatmaFatalError,

I'm very sorry! I misunderstood your PR. Now I saw your changes - I approve them and made the fix. 
You will be able to see the change on SAP Help Portal after the next content update.

Thanks for your contribution and I apologize again!
Best regards,
Gergana

**Pull request merged**
