### PR TITLE
Update create-a-communication-arrangement-b7a87fd.md

### PR DESCRIPTION
**Pull request by santoshmadhusudhana**
Removed unnecessary step (Incident ref: https://support.wdf.sap.corp/sap/support/message/2380062513)

### CODE REVIEW

**Comment by annawenger20** [comment]
Hi @santoshmadhusudhana , thanks a lot for your contribution. 
@Vikramkulkarni01 will take care of this. In the meantime, please our [Contributor License Agreement](https://cla-assistant.io/SAP-docs/btp-cloud-platform?pullRequest=162). 
Thanks, Anna

**Review by Vikramkulkarni01 — APPROVED** [review]
Hi, 
I'm approving the changes. Please merge it.

**Comment by Vikramkulkarni01** [comment]
Hi @santoshmadhusudhana, 
Thanks for the suggestion. The changes have been made in the help content and it will be available as part of the 2307a content release.

**Comment by nikolasimeonov77** [comment]
Hi @Vikramkulkarni01,
If you've completed the request, could you please merge it now?

Thanks!

Nikola

**Pull request merged**
