### PR TITLE
Change disk_limit from 4 to 10 gb

### PR DESCRIPTION
**Pull request by vlast3k**

### CODE REVIEW

**Comment by sdanter** [comment]
Change has been implemented for 9a release

**Review by sdanter — APPROVED** [review]

**Comment by sdanter** [comment]
Hi @vlast3k thank you for your feedback! The changes will be reflected on the Help Portal with the next release.

**Comment by silvestre** [comment]
@sdanter @vlast3k : I believe this change has only been implemented in the product for 10a, so the 9a documentation is now wrong.

**Comment by vlast3k** [comment]
@silvestre  this is true it comes with 10a, but i doubt someone will demand it so soon. The requirement comes from some CPI customers, which are anyway SaaS

**Pull request merged**
