### PR TITLE
fix: typo

### PR DESCRIPTION
**Pull request by BillyBouman-2B-IT**

### CODE REVIEW

**Comment by annawenger20** [comment]
Hi @BillyBouman-2B-IT 
thanks a lot for spotting this! Could you please sign our [Contributor License Agreement](https://cla-assistant.io/SAP-docs/btp-cloud-platform?pullRequest=165) so we can accept your proposal. 
Thanks, Anna

**Comment by boumanb** [comment]
@annawenger20 I've signed. No problem.

**Comment by BillyBouman-2B-IT** [comment]
@annawenger20  I've signed. No problem.

**Comment by YasminavanRooij** [comment]
Fixed the typo. The new documentation will be available with the next Help Portal update.

**Pull request merged**
