### PR TITLE
Update kyma-environment-468c2f3.md

### PR DESCRIPTION
**Pull request by marco-porru**
new description for the product

### CODE REVIEW

**Comment by marco-porru** [comment]
please replicate the same description here:

https://help.sap.com/docs/btp/migrating-from-neo-environment-to-multi-cloud-foundation-cloud-foundry-and-kyma/what-is-multi-cloud-foundation?version=Cloud#kyma-environment

**Comment by NHingerl** [comment]
Hi @marco-porru, I'd prefer to use product name variables wherever possible.
Please take a look at the following draft (screenshot from the backend) and let me know if it's not alright:

image

**Comment by NHingerl** [comment]
I updated the documentation. The changes will be visible to customers with the upcoming SAP BTP release.

**Comment by NHingerl** [comment]
Preview looks good for both.

- [Kyma Environment](https://help.sap.com/docs/btp/sap-business-technology-platform-internal/kyma-environment?locale=en-US&state=DRAFT&version=Internal)
- [What Is the Multi-Cloud Foundation](https://help.sap.com/docs/btp/migrating-from-neo-environment-to-multi-cloud-foundation-cloud-foundry-and-kyma/what-is-multi-cloud-foundation?locale=en-US&state=DRAFT&version=Dev) (Dev Draft)

**Review by NHingerl — APPROVED** [review]

**Pull request merged**
