### PR TITLE
Update getting-support-5dd7398.md

### PR DESCRIPTION
**Pull request by slavipande**
Added a sample line.

### CODE REVIEW

**Comment by slavipande** [comment]
> Thank you for your valuable content contribution, @slavipande! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://github.com/slavipande

**Comment by qmacro** [comment]
Hi @slavipande it's your SAP Community profile URL that's needed please, not your GitHub profile URL. Thanks.

**Comment by slavipande** [comment]
> Hi @slavipande it's your SAP Community profile URL that's needed please, not your GitHub profile URL. Thanks.

My bad, I replied again with the right link.

Thanks for the clarification, @qmacro 



> Thank you for your valuable content contribution, @slavipande! So that we can [recognize your contribution in SAP Community](https://github.com/SAP-docs/contribution-guidelines/blob/main/docs/recognition.md), please tell us your SAP Community profile URL in a reply to this comment; don't include any other text, just the URL on its own, like this:
> 
> ```
> https://people.sap.com/your-user-name
> ```
> 
> Thanks!

https://people.sap.com/slavipande22

**Comment by slavipande** [comment]
> Hi @slavipande it's your SAP Community profile URL that's needed please, not your GitHub profile URL. Thanks.

My bad. I replied again with the correct profile link.

Thanks for the note, @qmacro  :)

**Pull request closed without merging**
