### PR TITLE
remove unneeded "

### PR DESCRIPTION
**Pull request by bvarwig**

### CODE REVIEW

**Review by danielforsap — APPROVED** [review]

**Comment by nikolasimeonov77** [comment]
Hi @bvarwig,
Could you please sign [Contributor License Agreement](https://cla-assistant.io/SAP-docs/btp-cloud-platform?pullRequest=138) so that we can merge your proposals?

**Comment by bvarwig** [comment]
Hi @nikolasimeonov77 ,
I signed the Contributor License Agreement.

**Comment by bvarwig** [comment]
https://people.sap.com/britta.varwig

**Comment by bvarwig** [comment]
https://people.sap.com/britta.varwig

**Pull request merged**
